### ISSUE TITLE
Is it possible to develop and compile openmusic without Lispworks?

### ISSUE THREAD

**Issue by jgarte** [openmusic-project/openmusic#25]
Is it possible to develop and compile `openmusic` without Lispworks?

If not, is there any interest in moving away from LispWorks over the longterm in order to compile open music without depending on a proprietary lisp environment in order to build it?

I ask because I am interested in packaging openmusic for [guix](http://guix.gnu.org/). It is a free software distribution. I doubt they would accept a package that requires a proprietary lisp environment in order to build it from source.

I understand if this is not in the project's goals, also. I'm curious because it would be great to have `openmusic` packaged in a reproducible manner and with entirely free software.

**Comment by andersvi** [comment]
Hi jgarte.

> interest in moving away from LispWorks

In principle, yes.  It's been considered a few times, but quickly put aside, mainly because of lw's comprehensive cross platform support, esp. towards building advanced guis, making ports atm not realistic.  Perhaps more realistic would be to move towards other x-platform frameworks (eg. Clojure, Python...) in the future (om##-v.1.0?)

> packaging openmusic for guix. It is a free software distribution. I doubt they would accept a package that requires a proprietary lisp environment...

Fwiw, openmusic and om# are both licensed as GPL, and source code is available for anyone to use or modify, with the usual restrictions about retaining the license.  

Fedora and Ubuntu demand that source code is available with one of the free/open licenses (GPL, MIT...).  However, they (Fedora, guessing the same applies to Ubuntu) don't allow packages relying on closed-source compilers to build.

There's nothing against making them accessible via local repos.

Perhaps there are similar options for guix?

-anders

**Comment by jgarte** [comment]
@andersvi 

Thank you for your reply!

> esp. towards building advanced guis

Would one of these [guis](https://lispcookbook.github.io/cl-cookbook/gui.html) suffice as advanced enough for a port?

> Perhaps there are similar options for guix?

There is a [nonguix](https://gitlab.com/nonguix/nonguix.git) [channel](https://guix.gnu.org/manual/en/html_node/Channels.html).  These channels can be hosted by anyone and can federate through a [channels configuration file](https://guix.gnu.org/manual/en/html_node/Specifying-Additional-Channels.html)

> Nonguix is a software repository for the GNU Guix package manager, which packages some software which cannot be included in the official distribution for ethical or policy-related reasons.

**Comment by karimhaddad** [comment]
Dear jgarte,

Personally have started sometime ago ports using ltk and cl-cffi-gtk with some results but got stuck with the fact that these GUIs are not maintained anymore and they do lack some stability. As Anders states, for the time being CAPI is the most stable. supportive environment.

Best
K
PS: Since this is not an issue regarding OM's code i will soon class it as closed. I invite you if you need some further discussion on this topic which is really interesting to me and most the lisp community, to write on the discussion board here:  
https://discussion.forum.ircam.fr/c/openmusic/42
signing in is free
