### ISSUE TITLE
Reducetree

### ISSUE THREAD

**Issue by Nikoteemus** [openmusic-project/openmusic#36]
Hello,

It seems that in version 7.0 reducetree doesn't reduce the rests properly. Picture attached comparing the version 6-20 and 7.0
<img width="884" alt="Näyttökuva 2022-7-16 kello 2 33 32" src="https://user-images.githubusercontent.com/47433777/179324444-2a9abc30-ccb7-4f4f-b02c-bd2825649b95.png">
s

**Comment by karimhaddad** [comment]
Hi, 

Very strange. the code on both version is the same. Can you send us the tree structure (or the pathc) in order to see the difference. It might be something else. And please check if the tree structure is the same in both your OM versions.

Best
K

**Comment by karimhaddad** [comment]
Hi again, 

You are right. In om7 this happens to be wrong. It is fixed in the upcoming version.
For the moment you can put this .lisp file (after unzipping it) in your init folder inside your OM 7.0.app it will fix this issue
Best regards
K
[reducetreefix.lisp.zip](https://github.com/openmusic-project/openmusic/files/9125619/reducetreefix.lisp.zip)
