### ISSUE TITLE
cffi error with fluid_version_str on Windows 11

### ISSUE THREAD

**Issue by Seilburg** [openmusic-project/openmusic#46]
Hello,

I've created a new workspace with OM 7.2 on Windows 11 (22H2), and when I went to open the preferences from the workspace, I was issued the following error:
```
ERROR: Foreign function
cl-fluidsynth::|%cffi-foreign-function/FLUID_VERSION_STR|
trying to call to unresolved external function
"fluid_version_str"
```

It is impossible to access the preferences at this time. 
I tried installing Fluidsynth manually (via chocolately package manager), but this did not help.

All best,
Nigel

**Comment by karimhaddad** [comment]
Dear Nigel, 

This issue is solved in the actual sources. If you are using the 7.2 release, please download the attached file, unzip it and put it in the init folder in the OM
[fluid_fix.lisp.zip](https://github.com/openmusic-project/openmusic/files/12672865/fluid_fix.lisp.zip)
 application folder, then launch OM, it should fix this issue.

**Comment by Seilburg** [comment]
Thanks, that fixed it.
