### ISSUE TITLE
Chord-seq problem with different durations for a dyad

### ISSUE THREAD

**Issue by pouryafard75** [openmusic-project/openmusic#55]
Hello.

**Problem**: Chord-seq always selects the note with the shortest time-duration for the dyad and cannot handle different time durations from the list of lists (as opposed to the documentation).

**Steps to reproduce**: Use the zip file. [Issue.omp.zip](https://github.com/openmusic-project/openmusic/files/14395048/Issue.omp.zip)
<img width="396" alt="Screenshot 2024-02-24 at 9 19 57 PM" src="https://github.com/openmusic-project/openmusic/assets/28820932/7aa95710-9898-4bbf-a680-8f097e215a4b">

**Comment by karimhaddad** [comment]
Dear pouryafar, 

Sorry for this late reply.
Concerning this issue, it is not a bug but the expected behavior in case of "polyphony" in a chord-seq. VOICE not being a polyphonic object like POLY, the method chosen here is to take on the contrary the shortest duration so that the next expressed note will be "on time".
Can you point me to the documentation where this is not so? It might be a mistake or something did indeed change.
Thank you for reporting this issue.

Best
Karim

**Comment by pouryafard75** [comment]
@karimhaddad  

Chord-seq documentation as below:
<img width="1244" alt="image" src="https://github.com/openmusic-project/openmusic/assets/28820932/ccbf8bf3-484b-491c-b18a-1c14dc848fab">

**Comment by karimhaddad** [comment]
Hi, 

this is the online help documentation of the CHORD-SEQ editor. This is not related to the issue you are pointing to. The VOICE editor doesn't accept polyphony, that is the reason for its actual "behavior", taking the longest duration of a chord followed by a new one.

Best
K
