### ISSUE TITLE
Missing "omaudiolib" file and other weird errors

### ISSUE THREAD

**Issue by TromboneBoi9** [openmusic-project/openmusic#59]
Hello I rarely use Github for anything other than downloading so sorry if I look like an idiot.
I'm on Windows 10 by the way, 64-bit with an x64 processor.

I just now downloaded OpenMusic 7.4 from the releases page and while it installed fine, it's unable to run because of "Something wrong calling functions from omaudiolib:" and it shows a path to an _omaudiolib.dll_ file at `/WINDOWS/system32/omaudiolib.dll`. I checked that path in my file manager and it turns out the file doesn't exist.

Later after I create workspace, it gives another error about "trying to call to unresolved external function "openAudioManager"." From there the program just kinda sits there invisible so I have to close it with Task Manager.

**Comment by karimhaddad** [comment]
Dear TromboneBoi9, 

Sorry about that. 
First of all, yes it is normal that the dll is not in /WINDOWS/system32 path. No worry about that.
The problem comes from the omaudiolib.dll packaged in the windows release of version 7.4

Please follow the steps in the following post here (at the end of the post):
https://discussion.forum.ircam.fr/t/problem-finding-omaudiolib/36304/18

It should fix the issue.

Best Regards

karim
